[workspace]
resolver = "2"
members = [
    "npdf",
    "tiny-poppler",
    "simple-jpegli-enc",
]

[workspace.package]
version = "0.2.0-dev"
edition = "2024"
authors = ["noaione <noaione@n4o.xyz>"]
license = "GPL-3.0-or-later"
repository = "https://github.com/noaione/npdf"
homepage = "https://github.com/noaione/npdf"
rust-version = "1.88.0"

[workspace.dependencies]
rayon = "1.12.0"
sha2 = "0.10.9"  # for hashing purposes

# PDF and images
png = { version = "0.18.1" }
tiff = { version = "0.11.3", default-features = false, features = ["deflate", "lzw"] }
lopdf = { version = "0.40.0", default-features = false, features = ["rayon"] }
flate2 = "1.1.9" # for recompressing PDF stream

# CLI stuff
clap = { version = "4.6.1", features = ["derive"] }
inquire = "0.9.4"
crossbeam-channel = "0.5.15"
num_cpus = "1.17.0"
color-print = "0.3.7"

# Error handling
thiserror = "2.0.18"
color-eyre = { version = "0.6.5", default-features = false, features = ["track-caller"] }

# Build tools
cc = "1.2.60"
cmake = "0.1.58"
walkdir = "2.5.0"
glob = "0.3.3"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
debug = "limited"

[profile.dev]
debug = "full"
