[workspace]
resolver = "2"
members = [
    "npdf",
    "tiny-poppler",
]

[workspace.package]
version = "0.0.1-dev"
edition = "2024"
authors = ["noaione <noaione@n4o.xyz>"]
license = "GPL-3.0-or-later"
repository = "https://github.com/noaione/npdf"
homepage = "https://github.com/noaione/npdf"
rust-version = "1.88.0"
