[workspace]
resolver = "2"
members = [
    "npdf",
    "tiny-poppler",
    "simple-jpegli-enc",
]

[workspace.package]
version = "0.1.1-dev"
edition = "2024"
authors = ["noaione <noaione@n4o.xyz>"]
license = "GPL-3.0-or-later"
repository = "https://github.com/noaione/npdf"
homepage = "https://github.com/noaione/npdf"
rust-version = "1.88.0"

[workspace.dependencies]
rayon = "1.11.0"
thiserror = "2.0.17"
sha2 = "0.10.9"  # for hashing purposes

# PDF and images
png = { version = "0.18.0" }
tiff = { version = "0.10.3", default-features = false, features = ["deflate", "lzw"] }
lopdf = { version = "0.38.0", default-features = false, features = ["rayon"] }
flate2 = "1.1.5" # for recompressing PDF stream

# CLI stuff
clap = { version = "4.5.53", features = ["derive"] }
inquire = "0.9.1"
crossbeam-channel = "0.5.15"
num_cpus = "1.17.0"
color-print = "0.3.7"

# Build tools
cc = "1.2.51"
cmake = "0.1.57"
walkdir = "2.5.0"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1

[profile.dev]
debug = "full"
