[package]
name = "tiny-poppler"
version = "0.1.1"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true
keywords = ["library", "ffi", "pdf", "poppler", "renderer"]
description = "A tiny PDF rendering library based on Poppler C++ bindings."
readme = "./README.md"
# Do not include tests in crates.io package
exclude = [
    "tests/*",
]

[dependencies]
thiserror.workspace = true
rayon.workspace = true

simple-jpegli-enc = { path = "../simple-jpegli-enc" }
png.workspace = true
tiff.workspace = true

[features]
default = []
asan = ["simple-jpegli-enc/asan"]
lsan = ["simple-jpegli-enc/lsan"]
tsan = ["simple-jpegli-enc/tsan"]
ubsan = ["simple-jpegli-enc/ubsan"]

[build-dependencies]
cc.workspace = true
cmake.workspace = true
walkdir.workspace = true
glob.workspace = true
