[package]
name = "tiny-poppler"
version = "0.0.1"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true
keywords = ["library", "ffi", "pdf", "poppler", "renderer"]
description = "A tiny PDF rendering library based on Poppler C++ bindings."
readme = "./README.md"
# Do not include tests in crates.io package
exclude = [
    "tests/*",
]

[dependencies]
thiserror = "2.0.17"
png = { version = "0.18.0" }
jpeg-encoder = { version = "0.6.1", features = ["simd"] }
fax = "0.2.6"
tiff = { version = "0.10", default-features = false }

[features]
default = []
asan = []
lsan = []
tsan = []
ubsan = []

[build-dependencies]
cc = "1.0"
cmake = "0.1"
# vcpkg = "0.2"
