[package]
name = "tiny-poppler"
version = "0.0.1"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true
keywords = ["library", "ffi", "pdf", "poppler", "renderer"]
description = "A tiny PDF rendering library based on Poppler C++ bindings."
readme = "./README.md"
# Do not include tests in crates.io package
exclude = [
    "tests/*",
]

[dependencies]
thiserror = "1.0"
png = { version = "0.18.0" }

[build-dependencies]
cc = "1.0"
cmake = "0.1"
