[package]
name = "npdf"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true
keywords = ["cli", "pdf", "poppler", "export"]
description = "A simple PDF-to-PNG exporter tool built with on-top of Poppler."
readme = "./README.md"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
crossbeam-channel = "0.5.15"
num_cpus = "1.17.0"
color-print = "0.3.7"

tiny-poppler = { path = "../tiny-poppler" }
