[package]
name = "npdf"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true
keywords = ["cli", "pdf", "poppler", "export"]
description = "A simple PDF-to-PNG exporter tool built with on-top of Poppler."
readme = "./README.md"

[dependencies]
clap.workspace = true
clap_complete.workspace = true
inquire.workspace = true
crossbeam-channel.workspace = true
num_cpus.workspace = true
color-print.workspace = true
color-eyre.workspace = true
thiserror.workspace = true

tiny-poppler = { path = "../tiny-poppler" }
simple-jpegli-enc = { path = "../simple-jpegli-enc" }
lopdf.workspace = true
flate2.workspace = true
sha2.workspace = true

rayon.workspace = true
