[package]
name = "simple-jpegli-enc"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true
description = "A simple JPEG encoder using jpegli (libjxl)"
readme = "README.md"

[dependencies]
thiserror = "2.0"

[build-dependencies]
cmake = "0.1"
cc = "1.0"
walkdir = "1"
