name: build

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - '.vscode/**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - '.vscode/**'

env:
  POPPLER_VERSION: "25.11.0"

# Do not run concurrent builds
concurrency:
  group: "build-npdf-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    name: build (${{ matrix.os[1] }})
    runs-on: ${{ matrix.os[0] }}
    if: >
      github.event_name == 'push' ||
      contains(github.event.pull_request.body, '/build')
    strategy:
      fail-fast: false
      matrix:
        os:
          # Linux (x64)
          - [ubuntu-24.04, x86_64-unknown-linux-gnu]
          # # Linux (ARM64)
          # - [ubuntu-24.04-arm, aarch64-unknown-linux-gnu]
          # # macOS Apple Intel (Sonoma)
          # - [macos-15-intel, x86_64-apple-darwin]
          # macOS Apple Silicon (Tahoe)
          - [macos-26, aarch64-apple-darwin]
          # Windows Server 2025 (x64)
          - [windows-2025, x86_64-pc-windows-msvc]
          # # Windows 11 ARM (ARM64)
          # - [windows-11-arm, aarch64-pc-windows-msvc]

    env:
      CARGO_TERM_COLOR: always

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup rust cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "rustbuild-"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.12"

      - name: Install boost
        uses: MarkusJx/install-boost@v2
        id: install-boost
        with:
          boost_version: "1.89.0"

      - name: Install system dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            cmake \
            ninja-build \
            pkg-config \
            libexpat1-dev \
            libbrotli-dev \
            liblzma-dev \
            libbz2-dev \
            libfreetype6-dev \
            libfontconfig1-dev \
            libturbojpeg \
            libturbojpeg0-dev \
            libpng-dev \
            libtiff-dev \
            libopenjp2-7-dev \
            liblcms2-dev \
            libnss3-dev \
            libnspr4-dev

      - name: Install system dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install \
            cmake \
            ninja \
            pkg-config \
            bzip2 \
            brotli \
            xz \
            expat \
            freetype \
            fontconfig \
            jpeg-turbo \
            libpng \
            libtiff \
            openjpeg \
            lcms2 \
            nss \
            nspr

      - name: Cache vcpkg dependencies
        uses: actions/cache@v4
        if: runner.os == 'Windows'
        with:
          path: C:\vcpkg\installed
          key: vcpkg-${{ runner.os }}-${{ hashFiles('vcpkg.json') }}

      - name: Install system dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install ninja cmake pkgconfiglite -y --no-progress

          cd C:\vcpkg
          .\bootstrap-vcpkg.bat

          # Install some pre-dependencies
          C:\vcpkg\vcpkg.exe install bzip2:x64-windows-static brotli:x64-windows-static liblzma:x64-windows-static --clean-after-build

          # Install required packages as static libraries
          C:\vcpkg\vcpkg.exe install libpng:x64-windows-static zlib:x64-windows-static libiconv:x64-windows-static freetype:x64-windows-static tiff:x64-windows-static openjpeg:x64-windows-static libjpeg-turbo:x64-windows-static lcms:x64-windows-static --clean-after-build
          echo "VCPKG_ROOT=C:\vcpkg" >> $env:GITHUB_ENV
          echo "VCPKG_DEFAULT_TRIPLET=x64-windows-static" >> $env:GITHUB_ENV
          echo "VCPKG_FEATURE_FLAGS=manifests" >> $env:GITHUB_ENV

          # List manually installed packages for debugging
          echo "Installed vcpkg packages:"
          C:\vcpkg\vcpkg.exe list
          # dir C:\vcpkg\installed\x64-windows-static\bin
          dir C:\vcpkg\installed\x64-windows-static\lib

      - name: Build
        run: cargo build --profile release --workspace --all-targets -vv
        env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.boost_root }}
          Boost_DIR: ${{ steps.install-boost.outputs.boost_root }}
          CI_RUNNER: "github"

      - name: Compress artifacts
        run:
          uv run scripts/packer.py
        env:
          MATRIX_NAME: ${{ matrix.os[1] }}

      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: npdf-${{ matrix.os[1] }}
          path: |
            npdf-${{ matrix.os[1] }}.zip
            npdf-${{ matrix.os[1] }}.tar.gz
